<?php

namespace ArcaSolutions\ModStoresBundle\Plugins\InstantMessengerIntegration\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingInstantMessengerRepository extends EntityRepository
{
}
