<?php

namespace ArcaSolutions\ModStoresBundle\Plugins\InstantMessengerIntegration\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingLevelInstantMessengerRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getEnabledListingLevelsNameArray(){
        $qb = $this->createQueryBuilder('llim')
            ->select('l.name')
            ->innerJoin('ListingBundle:ListingLevel', 'l', 'WITH', 'l.value = llim.level' )
            ->where('llim.instantMessenger = :instantMessengerAvaiable')
            ->setParameter('instantMessengerAvaiable', 'y');

        return $qb->getQuery()->getArrayResult();
    }
}
