<?php

namespace ArcaSolutions\CoreBundle\Repository;

/**
 * AccountConsentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountConsentRepository extends \Doctrine\ORM\EntityRepository
{
}
