<?php

namespace ArcaSolutions\CoreBundle\Repository;

/**
 * ConsentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsentRepository extends \Doctrine\ORM\EntityRepository
{
}
