<?php

namespace ArcaSolutions\ModStoresBundle\Plugins\CommunityForum\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends EntityRepository
{

    /**
     * Returns module name in lowercase
     *
     * @return string
     */
    public function getModuleName()
    {
        return 'answer';
    }


    public function getLastAnswers($maxResults = 5)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->leftJoin(
                'CommunityForumBundle:Answer',
                'b',
                'WITH',
                'a.question = b.question AND a.id < b.id'
            )
            ->where("a.status = 'A'")
            ->andWhere('b.id is null')
            ->orderBy('a.id', 'DESC')
            ->groupBy('a.question')
            ->setMaxResults($maxResults);

        return $qb->getQuery()->getResult();
    }
}
