<?php

namespace ArcaSolutions\ModStoresBundle\Plugins\CommunityForum\Repository;

use ArcaSolutions\WebBundle\Repository\BaseCategoryRepository;
use Doctrine\ORM\EntityRepository;


/**
 * QuestionCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionCategoryRepository extends BaseCategoryRepository
{
    /**
     * Returns module name in lowercase
     *
     * @return string
     */
    public function getModuleName()
    {
        return 'question.category';
    }
}
