<?php

namespace ArcaSolutions\ModStoresBundle\Plugins\CommunityForum\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    /**
     * Returns module name in lowercase
     *
     * @return string
     */
    public function getModuleName()
    {
        return 'question';
    }
}
