<?php

namespace ArcaSolutions\ModStoresBundle\Plugins\DropdownMenu\Repository;


use ArcaSolutions\ModStoresBundle\Plugins\GeoTargetedBanner\Entity\DropdownMenu;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityRepository;


/**
 * DropdownMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DropdownMenuRepository extends EntityRepository
{
    public function getParentMenu()
    {
        $qb = $this->createQueryBuilder('b');

        $result = $qb->select('navbar.link, navbar.order, navbar.label, navbar.custom , b.parentMenu')
            ->where('navbar.area IN (\'header\', \'header_dropdown\') ')
            ->join('WebBundle:SettingNavigation', 'navbar', 'WITH', 'navbar.order = b.id')
            ->getQuery()
            ->getResult();

        return $result;
    }

    /**
     * Count entities (optionally filtered by a criteria)
     *
     * @param  array|Criteria $criteria
     *
     * @return int
     */
    public function countByCriteria($criteria = [])
    {
        return $this->_em->getUnitOfWork()->getEntityPersister($this->_entityName)->count($criteria);
    }
}
