<?php

namespace ArcaSolutions\ModStoresBundle\Plugins\MarketSelection\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * MarketSelectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketSelectionRepository extends EntityRepository
{
    public function getMarketSelection($domain = null, $level = 1)
    {
        return $this->createQueryBuilder('market')
            ->select('loc')
            ->andWhere('market.domainId = :domain')
            ->andWhere('market.locationLevel = :level')
            ->setParameter('domain', $domain)
            ->setParameter('level', $level)
            ->join('CoreBundle:Location'.$level, 'loc', 'WITH', 'loc.id = market.locationId')
            ->getQuery()
            ->getResult();
    }
}
