imports:
    - { resource: parameters.yml }
    - { resource: domain.yml }
    - { resource: security.yml }
    - { resource: database.yml }
    - { resource: search.yml }
    - { resource: pagination.yml }
    - { resource: api.yml }
    - { resource: liip.yml }

framework:
    #esi:             ~
    default_locale: "%locale%"
    translator:
        fallback: "en"
        enabled: true
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # It makes symfony's session works with php's session instead of its owner (We use it to get info about sitemgr)
        save_path: ~
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    port:       "%mailer_port%"
    encryption: "%mailer_encryption%"
    sender_address: "%mailer_sender%"
    auth_mode: "%mailer_auth_mode%"
    stream_options:
        ssl:
            verify_peer: false
            verify_peer_name: false

twig:
    strict_variables: false
    cache:            "%kernel.cache_dir%/twig"
    charset:          "%kernel.charset%"
    debug:            "%kernel.debug%"
    form:
        resources:
            - 'CoreBundle:Form:fields.html.twig'


assetic:
    debug: '%kernel.debug%'
    filters:
        cssrewrite: null
        lessphp:
            file: '%kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php'
            apply_to: \.less$
            formatter: compressed
            preserve_comments: false
            sourcemap: true

# Twig Extensions
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }

gregwar_captcha:
    quality: 100
    width: 150
    height: 40
    length: 6
    distortion: false
    background_color: [255,255,255]

ewz_recaptcha:
    public_key: ~
    private_key: ~
