<?php

namespace ArcaSolutions\ModStoresBundle\Plugins\YelpIntegration\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * YelpAccessTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YelpAccessTokenRepository extends EntityRepository
{

}
