<?php

namespace ArcaSolutions\ModStoresBundle\Plugins\YelpIntegration\Repository;

use ArcaSolutions\ModStoresBundle\Plugins\YelpIntegration\Entity\YelpCache;
use Doctrine\ORM\EntityRepository;


/**
 * YelpCacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YelpCacheRepository extends EntityRepository
{
    /**
     * @param array $searchCriteria
     * @param array $businesses
     * @param ObjectManager $em
     */
    public function save($searchCriteria, $businesses, $em)
    {
        $cache = new YelpCache();
        $cache->setSearchCriteria($searchCriteria);
        $cache->setResponse($businesses);
        $em->persist($cache);
        $em->flush($cache);
    }
}
