<?php

namespace ArcaSolutions\ModStoresBundle\Plugins\BrowseMapListing\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LocationBrowsebymap3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationBrowsebymap3Repository extends EntityRepository
{
}
