<?php

namespace ArcaSolutions\ModStoresBundle\Plugins\BrowseMapListing\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LocationRelated3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRelated3Repository extends EntityRepository
{
}
